
POST http://localhost:8000/vectorize HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "values": [
      {
        "recordId": "0",
        "data":
           {
             "url": "https://stgebaoai883.blob.core.windows.net/images/cats.jpg"
           }
      }
    ]
}

###

POST https://myskill.gentlebay-4474176e.westeurope.azurecontainerapps.io/vectorize HTTP/1.1
Host: myskill.gentlebay-4474176e.westeurope.azurecontainerapps.io
Content-Type: application/json

{
    "values": [
      {
        "recordId": "0",
        "data":
           {
             "url": "https://stgebaoai883.blob.core.windows.net/images/apple.jpg"
           }
      }
    ]
}